export default {
  SET_CHART_DATA: 'SET_CHART_DATA',
  SET_YEARS: 'SET_YEARS',
  SET_DATA_FREQUENCY: 'SET_DATA_FREQUENCY',
  SET_DATA_MONTH: 'SET_DATA_MONTH',
  SET_LAST_ERRORS: 'SET_LAST_ERRORS',
  SET_SELECTED_YEAR: 'SET_SELECTED_YEAR'
}
