const DATA_FREQUENCY = {
  YEARLY: 'YEARLY',
  MONTHLY: 'MONTHLY',
  WEEKLY: 'WEEKLY',
  DAILY: 'DAILY'
};

const TOTAL_DAYS_IN_YEAR = 365;

module.exports = {
  DATA_FREQUENCY,
  TOTAL_DAYS_IN_YEAR
};
